
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("addresses/new", "Create addresses")) ?>
</div>

<?php echo $this->tag->form(array("addresses/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search addresses</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="customer_id">Customer</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("customer_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="type">Type</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("type", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="address">Address</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("address", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="additional_info">Additional Of Info</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("additional_info", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="zipcode">Zipcode</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("zipcode", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="rural">Rural</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("rural", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="district">District</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("district", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="city">City</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("city", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="province">Province</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("province", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="country">Country</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("country", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="phone">Phone</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("phone", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="mobile">Mobile</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("mobile", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="shipping">Shipping</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("shipping", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="billing">Billing</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("billing", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_date">Created Of Date</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_date", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_updated_date">Last Of Updated Of Date</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_updated_date", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
